// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgKrSrKgYJISDuVGDt7emqm1NKLs6dyDc',
    appId: '1:125751913781:web:c83295986783237a2cf07c',
    messagingSenderId: '125751913781',
    projectId: 'earth-solution-system',
    authDomain: 'earth-solution-system.firebaseapp.com',
    storageBucket: 'earth-solution-system.appspot.com',
    measurementId: 'G-0WZMGMB1HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgLvUjSXW-NILSpcqr34FPPAHJbXatwA',
    appId: '1:125751913781:android:fe93c4eb33525be22cf07c',
    messagingSenderId: '125751913781',
    projectId: 'earth-solution-system',
    storageBucket: 'earth-solution-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEVvl3am6ZgvodRFHd18U9_-FY9ifF2bQ',
    appId: '1:125751913781:ios:be55305a56072df92cf07c',
    messagingSenderId: '125751913781',
    projectId: 'earth-solution-system',
    storageBucket: 'earth-solution-system.appspot.com',
    iosBundleId: 'com.ess.earthSolutionSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEVvl3am6ZgvodRFHd18U9_-FY9ifF2bQ',
    appId: '1:125751913781:ios:e4b2836a5df515f92cf07c',
    messagingSenderId: '125751913781',
    projectId: 'earth-solution-system',
    storageBucket: 'earth-solution-system.appspot.com',
    iosBundleId: 'com.ess.earthSolutionSystem.RunnerTests',
  );
}
